name = "CSCReactor_jlOs"
uuid = "388fa371-fe3d-443c-9121-b1096b353e97"
authors = ["josePereiro <jose.pereiro.personal@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
